name: Metrics
on:
  schedule:
    - cron: "0 0,12 * * *" # Runs at 00:00 and 12:00 UTC
  push: {branches: ["master", "main"]}
  workflow_dispatch: # Allows manual trigger for testing
jobs:
  github-metrics:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your Personal Access Token (stored in Secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          # Automatic GitHub token for committing the result
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: pixel-87
          template: classic
          base: header, activity, community, repositories
          config_animations: yes
          config_timezone: Europe/London
          
          # Optimization settings
          optimize: yes
          use_prebuilt_image: yes # Uses the pre-compiled Docker image to save build time

          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_traffic: yes
